[package]
name = "lle_gui"
version = "0.1.0"
authors = ["ITOAR <itoar@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
egui = "0.21.0"
eframe = { version = "^0.21", features = ["persistence"] }
serde = { version = "1", features = [
    "derive",
] } # You only need this if you want app persistence
lle = { git = "https://github.com/TsuITOAR/Lle.git" }
rand = "^0.8"
anyhow = "*"
log = "^0.4"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"
wasm-bindgen-futures = "0.4"
getrandom = { version = "^0.2", features = ["js"] }

[profile.release]
opt-level = 2 # fast and small wasm
