[package]
name = "lle_gui"
version = "0.1.0"
authors = ["ITOAR <itoar@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
egui = "^0.19"
eframe = { version = "^0.19", features = ["persistence"] }
serde = { version = "1", features = [
    "derive",
] } # You only need this if you want app persistence
lle = { git = "https://github.com/TsuITOAR/Lle.git" }
jkplot = { git = "https://github.com/TsuITOAR/jkplot.git" }
rand = "^0.8"
plotters = "^0.3"
plotters-bitmap = "^0.3"
anyhow = "*"
log = "^0.4"
# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"


[profile.release]
opt-level = 2 # fast and small wasm
